version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 9624
      POSTGRES_DB: AToyDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - app-network

  identityserver:
    build:
      context: ./AToyStore.IdentityServer
      dockerfile: IdentityServer/Dockerfile
    container_name: identityserver
    ports:
      - "8000:8000"
    environment:
      - ASPNETCORE_URLS=http://+:8000
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=AToyDB;Username=postgres;Password=9624
      - JwtSettings__Issuer=https://atoystore.store/auth
      - JwtSettings__Audience=https://atoystore.store
    depends_on:
      - postgres
    restart: always
    networks:
      - app-network

  api:
    build:
      context: ./AToyStore.API
      dockerfile: AToyStore.API/Dockerfile
    container_name: api
    ports:
      - "8001:8001"
    environment:
      - ASPNETCORE_URLS=http://+:8001
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=AToyDB;Username=postgres;Password=9624
      - IdentityServer__Authority=https://atoystore.store/auth
    depends_on:
      - postgres
    volumes:
      - /home/uploads:/app/wwwroot/uploads
    restart: always
    networks:
      - app-network

  frontend:
    build:
      context: ./atoystore-client
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
      - "443:443"
    environment:
      - REACT_APP_API_URL=https://atoystore.store/api
      - REACT_APP_AUTH_URL=https://atoystore.store/auth
    depends_on:
      - identityserver
      - api
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:rw
    restart: always
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email your-email@example.com --agree-tos --no-eff-email --force-renewal -d atoystore.store -d www.atoystore.store
    networks:
      - app-network

volumes:
  postgres_data:
  certbot-etc:
  certbot-var:

networks:
  app-network:
    driver: bridge